require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'whichdayz' do
  config=use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


# Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'

# Creating the Development Environment (in other words, Bringing in the Library&&Dependencies to the project)
  pod 'Firebase/Firestore'

# GOOGLE SIGN-IN SDK (Library&&Dependencies for Google's earlier OAuth2.0 initiative)
# BASED ON https://github.com/react-native-community/google-signin/blob/master/docs/ios-guide.md#install-google-sign-in-sdk
  pod 'GoogleSignIn', '~> 5.0.2'
  
# I brought this Library in because apparently the ReactNative version 0.63.3 inherited files are broken.
  pod 'leveldb-library', '~> 1.22'


  target 'whichdayzTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'whichdayz-tvOS' do
  # Pods for whichdayz-tvOS

  target 'whichdayz-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end